---
    - name: "Setting up packages on server"
      become: yes
      apt:
        update_cache: yes 
    - name: "Remove dependencies"
      become: yes
      apt:
        autoremove: yes  # removing old dependencies
  
    - name: "update system."
      become: yes
      apt: # update environment
        update_cache: yes
 
    - name: "install python and nodejs"
      become: yes
      apt:
        name: ["nodejs", "npm"]
        state: latest
        update_cache: yes
    - name: "installing python"
      become: yes
      apt:
        name: "python"
        state: latest
    - name: "installing pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present
    - name: running the backend
      shell: |
        npm install
        pm2 start "npm start" --name backend
    - name: " installing typescript for Database migration"
      become: yes
      npm:
        name: typescript
        global: yes
        production: yes
        state: present
    - name: Database migration task
      shell: |
        cd backend
        npm install
        npm audit fix
        npm run migrations > ~/db_migrated.txt # this should show proof of migration
        echo " Migration for job ${CIRCLE_JOB} with migration ID << pipeline.id >>_migrations" >db_migrated.txt

    - name: Build and copy backend compiled files to server
      shell: |
        cd /src/project/backendbackend
        npm install
        npm audit fix --audit-level=critical --force
        npm run build
        mkdir ~/udaPeople/backendCopies
    - name: copy files 
      copy:
        src: backend/dist
        dest: ~/udaPeople/backend/backendCopies
        force: yes
          
         


   
  