---
    - name: "Setting up packages on server"
      become: yes
      apt:
        update_cache: yes 
    - name: "Remove dependencies"
      become: yes
      apt:
        autoremove: yes  # removing old dependencies
  
    - name: "install dependencies."
      become: yes
      apt: # update environment
        name: ["update","upgrade"]
  
  
    - name: "install python and nodejs"
      become: yes
      apt:
        name: ["python","nodejs", "npm"]
        state: latest
        update_cache: yes
    - name: "installing pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present
    - name: running the backend
      shell: |
        npm install
        pm2 start "npm start" --name backend

   
  