---
    - name: "Setting up packages on server"
      become: yes
      apt:
        update_cache: yes 
    - name: "Remove dependencies"
      become: yes
      apt:
        autoremove: yes  # removing old dependencies
  
    - name: "update system."
      become: yes
      apt: # update environment
        update_cache: yes
 
    - name: "install python and nodejs"
      become: yes
      apt:
        name: ["nodejs", "npm"]
        state: latest
        update_cache: yes
    - name: "installing python"
      become: yes
      apt:
        name: "python"
        state: latest
    - name: "installing pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present
    - name: running the backend
      shell: |
        npm install
        pm2 start "npm start" --name backend
    - name: " installing typescript for Database migration"
      become: yes
      npm:
        name: typescript
        global: yes
        production: yes
        state: present

   
  