---
    - name: "Setting up packages on server"
      become: yes
      apt:
        update_cache: yes 
    - name: "Remove dependencies"
      become: yes
      apt:
        autoremove: yes  # removing old dependencies
  
    - name: "install dependencies."
      become: yes
      apt: # update environment
        name: ["update","upgrade"]
  
  
    - name: "install python and nodejs"
      become: yes
      apt:
        name: ["python","nodejs", "npm"]
        state: latest
        update_cache: yes
    - name: "installing pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present
    
    - name: installing more packages
      become: yes
      ignore_errors: true
        - . ~/.nvm/nvm.sh
        - pm2 start "npm start" --name backend
        - args:
            chdir: ~/udaPeople/backend/
            executable: /bin/bash
        # clone project from github
        - git: 
            dest: /src/project
            repo: "https://github.com/pius-ng3a/cloud_deployment_udacity.git"
            version: master
            shell: |
                cd /src/project/backend
                npm i 
                pm2 startup 
                pm2 start npm --name \"backend\" -- start"
                copy: #copy environment variables from .env file
                src: backend/.env
                dest: ~/udaPeople/backend/.env
            force: yes
  