---
     
    - name: installing more packages
      ignore_errors: true
        - . ~/.nvm/nvm.sh
        - pm2 start "npm start" --name backend
        - args:
            chdir: ~/udaPeople/backend/
            executable: /bin/bash
        # clone project from github
        - git: 
            dest: /src/project
            repo: "https://github.com/pius-ng3a/cloud_deployment_udacity.git"
          version: master
          shell: |
            cd /src/project/backend
            npm i 
            pm2 startup 
            pm2 start npm --name \"backend\" -- start"
          copy: #copy environment variables from .env file
            src: backend/.env
            dest: ~/udaPeople/backend/.env
            force: yes
